apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-minio-{{ namespace }}
  namespace: {{ namespace }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 8g
spec:
  rules:
    - host: {{ host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ tenantName }}-internal-service
              servicePort: 9000
  tls:
    - hosts:
      - {{ host }}
      secretName: {{ host }}-tls